modLoader="javafml" #mandatory
loaderVersion="[40,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"
[[mods]] #mandatory
modId="lexium" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Lexium" #mandatory
logoFile="examplemod.png" #optional
credits="LadyLexxie" #optional
authors="Love, Cheese and small house plants" #optional
description='''
'''
[[dependencies.lexium]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[40,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.lexium]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
